///|
pub const DefaultColor : Int = 0

///|
pub const DefaultAttr : Int = 256

///|
pub const NullCellChar : String = ""

///|
pub const NullCellWidth : Int = 1

///|
pub const NullCellCode : Int = 0

///|
pub const WhitespaceCellChar : String = " "

///|
pub const WhitespaceCellWidth : Int = 1

///|
pub const WhitespaceCellCode : Int = 32

///|
pub const ContentCodepointMask : Int = 0x1FFFFF

///|
pub const ContentIsCombinedMask : Int = 0x200000

///|
pub const ContentHasContentMask : Int = 0x3FFFFF

///|
pub const ContentWidthMask : Int = 0xC00000

///|
pub const ContentWidthShift : Int = 22

///|
pub const PcolorMask : Int = 0xFF

///|
pub const RgbMask : Int = 0xFFFFFF

///|
pub const CmMask : Int = 0x3000000

///|
pub const CmDefault : Int = 0

///|
pub const CmP16 : Int = 0x1000000

///|
pub const CmP256 : Int = 0x2000000

///|
pub const CmRgb : Int = 0x3000000

///|
pub const RedShift : Int = 16

///|
pub const GreenShift : Int = 8

///|
pub const BlueShift : Int = 0

///|
pub const FgInverse : Int = 0x4000000

///|
pub const FgBold : Int = 0x8000000

///|
pub const FgUnderline : Int = 0x10000000

///|
pub const FgBlink : Int = 0x20000000

///|
pub const FgInvisible : Int = 0x40000000

///|
pub const BgItalic : Int = 0x4000000

///|
pub const BgDim : Int = 0x8000000

///|
pub const BgHasExtended : Int = 0x10000000

///|
pub const BgProtected : Int = 0x20000000

///|
pub const BgOverline : Int = 0x40000000

///|
pub const UnderlineStyleMask : Int = 0x1C000000
